import { useEffect, useState } from 'react';
import { api } from '../api/client';
import type {
  RcaResult,
  SpotFixProposal,
  SpotFixEdit,
  SpotFixConsensus,
  SpotFixEvidence,
  SpotFixEvidenceCheck,
  SpotFixVerification,
  TestRecord,
} from '../api/types';
import { CopyButton } from './CopyButton';

/**
 * Human-approval gate for an AI-proposed source edit.
 *
 * Nothing here writes to disk on its own: generating a proposal is read-only,
 * and the diff is shown so a person decides. The risk warnings matter — a
 * model will sometimes "fix" a test by rewriting what it asserts, which
 * silently destroys the test's value, so those edits are called out rather
 * than left for the reviewer to notice.
 */

/**
 * Shows what the live-runtime probe actually found for this edit's proposed
 * selector(s) — real corroboration (or a real warning) from a headless
 * browser checked against the live app a moment ago, not another guess.
 * Only rendered when a probe actually ran (edit.liveProbe present); most
 * edits either don't touch a selector or had no captured page URL to check
 * against, and stay silent here rather than implying a check that didn't
 * happen.
 */
function LiveProbeNote({ liveProbe }: { liveProbe: NonNullable<SpotFixEdit['liveProbe']> }) {
  const describe = (c: { selector: string; count: number | null; error: string | null }) =>
    c.error ? `"${c.selector}" — invalid selector (${c.error})` : `"${c.selector}" → ${c.count} element${c.count === 1 ? '' : 's'}`;

  const worstNew = liveProbe.new.some((c) => c.count === 0 || c.error) ? 'warn' : 'ok';

  return (
    <div className={`spotfix-live-probe spotfix-live-probe-${worstNew}`} title={`Checked live at ${liveProbe.landedUrl}`}>
      {worstNew === 'ok' ? '✓' : '⚠'} Live check: {liveProbe.new.map(describe).join(', ')}
      {liveProbe.old.length > 0 && (
        <span className="muted"> (previous selector: {liveProbe.old.map(describe).join(', ')})</span>
      )}
    </div>
  );
}

/**
 * A locator line the model copied from the compact catalog rendering rather
 * than the real file was rewritten to match the file's actual text before
 * this diff was built — see lib/spotfix/locatorRecovery.js. Shown so that
 * correction is visible rather than silently baked into the diff above.
 */
function RecoveredLinesNote({ recovered }: { recovered: NonNullable<SpotFixEdit['recovered']> }) {
  return (
    <div className="spotfix-recovered">
      <div className="spotfix-recovered-title">ℹ Formatting auto-corrected to match the real source</div>
      <ul>
        {recovered.map((r) => (
          <li key={r.name}>
            <code>this.{r.name}</code> — the model's copy of this line didn't match the file byte-for-byte
            (likely copied from the compact locator list rather than the source itself); corrected automatically.
            No behaviour changed.
          </li>
        ))}
      </ul>
    </div>
  );
}

function DiffView({ edit }: { edit: SpotFixEdit }) {
  return (
    <div className="spotfix-diff">
      <div className="spotfix-diff-header">
        <code>{edit.file}</code>
        <CopyButton value={edit.newCode} label="Copy new code" />
      </div>
      {edit.reason && <div className="spotfix-edit-reason">{edit.reason}</div>}
      {edit.recovered && edit.recovered.length > 0 && <RecoveredLinesNote recovered={edit.recovered} />}
      <pre className="spotfix-diff-body">
        {edit.diff.map((row, i) => (
          <div key={i} className={`diff-row diff-${row.type}`}>
            <span className="diff-gutter">{row.type === 'add' ? '+' : row.type === 'remove' ? '-' : ' '}</span>
            <span className="diff-text">{row.text || ' '}</span>
          </div>
        ))}
      </pre>
      {edit.liveProbe && <LiveProbeNote liveProbe={edit.liveProbe} />}
    </div>
  );
}

/**
 * Real, measured confidence — N independently-generated, independently
 * grounding-checked candidates converging on the same edit — shown
 * alongside (not instead of) the model's own self-reported confidence,
 * which this exists precisely because self-reports aren't reliable enough
 * alone. Only appears when escalation actually happened (a high-risk edit
 * or a test with prior failed attempts); most proposals won't have one.
 */
function ConsensusBadge({ consensus }: { consensus: SpotFixConsensus }) {
  if (!consensus.disagreed) {
    return (
      <span
        className="spotfix-consensus spotfix-consensus-agree"
        title={`Independently generated by ${consensus.models.join(' and ')} — both arrived at the same edit.`}
      >
        ✓ {consensus.agreeing}/{consensus.total} models agree
      </span>
    );
  }
  return (
    <span
      className="spotfix-consensus spotfix-consensus-disagree"
      title={`Asked: ${consensus.allModelsAsked.join(', ')}. Only ${consensus.models.join(' and ')} (${consensus.agreeing}/${consensus.total}) agree on the edit shown — review this one more carefully than usual.`}
    >
      ⚠ models disagreed ({consensus.agreeing}/{consensus.total})
    </span>
  );
}

function riskList(edits: SpotFixEdit[]) {
  // De-duplicate by risk id: the same warning across two edits reads as noise.
  return [...new Map(edits.flatMap((e) => e.risks.map((r) => [r.id, r]))).values()];
}

const EVIDENCE_ICON: Record<SpotFixEvidenceCheck['status'], string> = {
  pass: '✓',
  fail: '✕',
  unknown: '?',
  'not-applicable': '–',
};

const STRENGTH_HEADING: Record<SpotFixEvidence['strength'], string> = {
  'well-evidenced': 'Everything that could be checked, was',
  'partially-checked': 'Partly checked',
  contradicted: 'Evidence against this fix',
};

/**
 * The audit trail: what was checked, what each check found, and what could not
 * be checked at all.
 *
 * Collapsed by default so it never competes with the diff — but the headline
 * count is always visible, because "4 passed, 3 could not be run" and "7
 * passed" are different claims and the previous UI showed both as an absence
 * of warnings.
 */
function EvidenceLedger({ evidence, verification }: { evidence?: SpotFixEvidence | null; verification?: SpotFixVerification | null }) {
  const [open, setOpen] = useState(false);
  if (!evidence) return null;

  const { counts } = evidence;
  const parts = [
    `${counts.pass} passed`,
    counts.fail ? `${counts.fail} failed` : null,
    counts.unknown ? `${counts.unknown} not checkable` : null,
  ].filter(Boolean);

  return (
    <div className={`spotfix-evidence is-${evidence.strength}`}>
      <button type="button" className="spotfix-evidence-header" onClick={() => setOpen((v) => !v)} aria-expanded={open}>
        <span className="spotfix-evidence-heading">{STRENGTH_HEADING[evidence.strength]}</span>
        <span className="spotfix-evidence-counts">{parts.join(' · ')}</span>
        <span className="spotfix-evidence-toggle">{open ? 'Hide detail' : 'Show detail'}</span>
      </button>
      <p className="spotfix-evidence-summary">{evidence.summary}</p>
      {open && (
        <ul className="spotfix-evidence-list">
          {evidence.checks.map((c) => (
            <li key={c.id} className={`is-${c.status}`}>
              <span className="spotfix-evidence-icon" aria-hidden="true">
                {EVIDENCE_ICON[c.status]}
              </span>
              <span>
                <strong>{c.label}</strong>
                {c.status === 'unknown' && ' — could not be checked'}
                <br />
                <span className="spotfix-evidence-detail">{c.detail}</span>
              </span>
            </li>
          ))}
          {/* The rerun is the one check that only exists after applying, so it
              is appended here rather than baked into the stored ledger. */}
          {verification && verification.status !== 'pending' && (
            <li className={`is-${verification.status === 'passed' ? 'pass' : verification.status === 'inconclusive' ? 'unknown' : 'fail'}`}>
              <span className="spotfix-evidence-icon" aria-hidden="true">
                {verification.status === 'passed' ? '✓' : verification.status === 'inconclusive' ? '?' : '✕'}
              </span>
              <span>
                <strong>The test passes with this fix applied</strong>
                <br />
                <span className="spotfix-evidence-detail">{verification.detail}</span>
              </span>
            </li>
          )}
        </ul>
      )}
    </div>
  );
}

function RiskWarnings({ edits }: { edits: SpotFixEdit[] }) {
  const risks = riskList(edits);
  if (!risks.length) return null;
  const high = risks.filter((r) => r.severity === 'high');
  const low = risks.filter((r) => r.severity !== 'high');

  return (
    <div className="spotfix-risks">
      {high.length > 0 && (
        <>
          <div className="spotfix-risks-title spotfix-risks-title-high">
            ⛔ This changes what the test checks — cannot apply without confirming below
          </div>
          <ul>
            {high.map((risk) => (
              <li key={risk.id}>
                <strong>{risk.label}.</strong> {risk.detail}
              </li>
            ))}
          </ul>
        </>
      )}
      {low.length > 0 && (
        <>
          <div className="spotfix-risks-title">⚠ Review before applying</div>
          <ul>
            {low.map((risk) => (
              <li key={risk.id}>
                <strong>{risk.label}.</strong> {risk.detail}
              </li>
            ))}
          </ul>
        </>
      )}
    </div>
  );
}

export function SpotFixPanel({
  test,
  runId,
  rca,
}: {
  test: TestRecord;
  runId: string;
  rca: RcaResult | null | undefined;
}) {
  const [proposal, setProposal] = useState<SpotFixProposal | null | undefined>(test.spotFix);
  const [busy, setBusy] = useState<'propose' | 'apply' | 'apply-rerun' | 'revert' | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [riskAcknowledged, setRiskAcknowledged] = useState(false);

  // Picks up updates that land after this panel already mounted — most
  // importantly, a verification rerun resolving from 'pending' to
  // 'passed'/'failed'. That now happens without navigating away (see
  // handleApply below), so this is what makes the result actually show up
  // instead of leaving "⏳ Rerunning…" stuck on screen.
  useEffect(() => {
    setProposal(test.spotFix);
  }, [test.spotFix]);

  // A spot fix only makes sense for a code-level cause, and the server
  // enforces the same rule — this just avoids offering a button that would
  // always come back declining.
  const isCodeIssue = rca?.category === 'code';

  async function handlePropose() {
    setBusy('propose');
    setError(null);
    setRiskAcknowledged(false);
    try {
      setProposal(await api.proposeSpotFix(runId, test.testId));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate a spot fix');
    } finally {
      setBusy(null);
    }
  }

  async function handleApply(rerun: boolean, verify = false) {
    setBusy(rerun ? 'apply-rerun' : 'apply');
    setError(null);
    try {
      const result = await api.applySpotFix(runId, test.testId, rerun, verify, riskAcknowledged);
      // Stays on this run rather than jumping to the new rerun's page —
      // that would hide every other failure being worked through here.
      // The verification rerun happens in the background; this test's own
      // row shows "⏳ Rerunning…" and updates itself once it resolves (see
      // the sync effect above), the same way a plain "Rerun test" does.
      setProposal((prev) =>
        prev
          ? { ...prev, applied: result.applied, reverted: null, verification: verify ? { status: 'pending' } : null }
          : prev
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not apply the spot fix');
    } finally {
      setBusy(null);
    }
  }

  async function handleRevert() {
    setBusy('revert');
    setError(null);
    try {
      const result = await api.revertSpotFix(runId, test.testId);
      setProposal((prev) => (prev ? { ...prev, applied: null, reverted: result } : prev));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not revert the spot fix');
    } finally {
      setBusy(null);
    }
  }

  if (!rca) return null;

  if (!isCodeIssue) {
    return (
      <div className="spotfix-section">
        <div className="spotfix-unavailable">
          No spot fix offered — this failure is categorised as <strong>{rca.category}</strong>, not a code issue, so
          there is nothing in the repo to change.
        </div>
      </div>
    );
  }

  const applied = proposal?.applied;
  const verification = proposal?.verification;
  const highRisks = proposal?.available ? riskList(proposal.edits).filter((r) => r.severity === 'high') : [];
  const highRisk = highRisks.length > 0;
  // Two different kinds of edit reach this gate and they need different
  // wording. One rewrites what the test checks; the other keeps the check
  // intact but breaks the project's layering (a selector or wait pushed into
  // a spec file — see lib/spotfix/layering.js). Telling someone they're
  // hiding a bug when they're actually approving a misplaced locator makes
  // the warning easy to dismiss, which is the one thing it must not be.
  const architectureOnly = highRisks.every((r) =>
    ['locator-in-spec', 'wait-in-spec', 'dom-query-in-spec', 'playwright-import-in-spec', 'playwright-in-business-function'].includes(r.id)
  );

  return (
    <div className="spotfix-section">
      {!proposal && (
        <button className="secondary-button" onClick={handlePropose} disabled={busy !== null}>
          {busy === 'propose' ? 'Generating spot fix…' : 'Propose spot fix'}
        </button>
      )}

      {error && <div className="rca-error">{error}</div>}

      {proposal && !proposal.available && (
        <div className="spotfix-unavailable">
          <div>No spot fix offered — {proposal.reason}</div>
          <button className="link-button" onClick={handlePropose} disabled={busy !== null}>
            {busy === 'propose' ? 'Retrying…' : 'Try again'}
          </button>
        </div>
      )}

      {proposal?.available && (
        <div className="spotfix-result">
          <div className="spotfix-header">
            <span className="spotfix-title">Proposed fix</span>
            <span className={`spotfix-confidence spotfix-confidence-${proposal.confidence}`}>
              {proposal.confidence} confidence
            </span>
            {proposal.consensus && <ConsensusBadge consensus={proposal.consensus} />}
            {proposal.model && <span className="muted">{proposal.model}</span>}
          </div>

          {proposal.consensus?.disagreed && (
            <div className="spotfix-disagreement">
              ⚠ Asked {proposal.consensus.allModelsAsked.length} independent models — only{' '}
              {proposal.consensus.models.join(' and ')} agreed on the edit shown below. The others proposed something
              different, which they'd only do if there's real ambiguity here. Read this one more carefully than usual
              before applying.
            </div>
          )}

          {proposal.explanation && <p className="spotfix-explanation">{proposal.explanation}</p>}

          <RiskWarnings edits={proposal.edits} />
          <EvidenceLedger evidence={proposal.evidence} verification={verification} />

          {proposal.edits.map((edit) => (
            <DiffView key={`${edit.file}-${edit.oldCode.slice(0, 40)}`} edit={edit} />
          ))}

          {proposal.rejected && proposal.rejected.length > 0 && (
            <div className="spotfix-rejected">
              Some proposed edits were discarded because they could not be verified against the source:
              <ul>
                {proposal.rejected.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ul>
            </div>
          )}

          {verification && (
            <div className={`spotfix-verification is-${verification.status}`}>
              {verification.status === 'pending' && '⏳ Rerunning to check this fix — it will be undone automatically unless the test passes.'}
              {verification.status === 'passed' && highRisk &&
                (architectureOnly
                  ? `✓ The rerun passed — but it only proves the test is green, not that the change belongs where it was made. The architecture warning above still stands. ${verification.detail || ''}`
                  : `✓ The rerun passed — but this edit changed what's expected, so that was never in doubt. It does not confirm the fix is correct. ${verification.detail || ''}`)}
              {verification.status === 'passed' && !highRisk && `✓ Verified — ${verification.detail}`}
              {verification.status === 'inconclusive' && (
                <>
                  {`⚠ Passed, but NOT verified — ${verification.detail}`}
                  {verification.unvalidatable?.length ? (
                    <ul className="spotfix-unvalidatable">
                      {verification.unvalidatable.map((u) => (
                        <li key={u.id}>
                          <strong>{u.label}.</strong> A rerun cannot settle this because {u.why}.
                        </li>
                      ))}
                    </ul>
                  ) : null}
                </>
              )}
              {verification.status === 'failed' && `✕ Not verified — ${verification.detail}`}
            </div>
          )}

          {applied ? (
            <div className="spotfix-applied">
              <div>
                ✓ Applied to {applied.files.map((f) => f.file).join(', ')}. If the rerun still fails, undo it here or
                from the banner at the top of the page — review in git before committing either way.
              </div>
              <button className="secondary-button" onClick={handleRevert} disabled={busy !== null}>
                {busy === 'revert' ? 'Reverting…' : 'Revert this change'}
              </button>
            </div>
          ) : (
            <div className="spotfix-actions-wrap">
              {highRisk && (
                <label className="spotfix-risk-ack">
                  <input
                    type="checkbox"
                    checked={riskAcknowledged}
                    onChange={(e) => setRiskAcknowledged(e.target.checked)}
                  />
                  {architectureOnly
                    ? "I've reviewed this — it breaks the project's test architecture rules, and I've confirmed that's acceptable here rather than something to move into the right layer."
                    : "I've reviewed this — it changes the test's expectations rather than fixing the app, and I've confirmed that's the right call here, not a bug being hidden."}
                </label>
              )}
              <div className="spotfix-actions">
                {/* Default action is the verified one: an AI fix is a guess until
                    a rerun proves it, so keeping it should be the deliberate
                    fallback rather than the easy path. Not a meaningful signal
                    for a high-risk edit though — see the title/tooltip. */}
                <button
                  className="primary-button"
                  onClick={() => handleApply(true, true)}
                  disabled={busy !== null || (highRisk && !riskAcknowledged)}
                  title={
                    highRisk
                      ? 'A passing rerun does not validate this edit — it will pass by construction. Confirm above before applying.'
                      : 'Applies the fix, reruns the test, and undoes the change automatically unless it passes'
                  }
                >
                  {busy === 'apply-rerun' ? 'Applying…' : 'Apply & verify'}
                </button>
                <button
                  className="secondary-button"
                  onClick={() => handleApply(false)}
                  disabled={busy !== null || (highRisk && !riskAcknowledged)}
                >
                  {busy === 'apply' ? 'Applying…' : 'Apply without rerunning'}
                </button>
                <button className="link-button" onClick={handlePropose} disabled={busy !== null}>
                  {busy === 'propose' ? 'Regenerating…' : 'Regenerate'}
                </button>
              </div>
            </div>
          )}

          {proposal.reverted && (
            <div className="spotfix-reverted">
              Reverted {proposal.reverted.reverted.join(', ')}.
              {proposal.reverted.skipped.length > 0 && ` Skipped: ${proposal.reverted.skipped.join('; ')}.`}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
